{
    "name": "libidn2",
    "ecosystem": "pypi",
    "campaign": "2025-10-bugdotexe",
    "affected_versions": [
        "2.3.2",
        "2.3.4"
    ],
    "campaign_assigned_at": "2025-10-29T22:07:25.911413+00:00",
    "campaign_data_modified_at": "2025-10-30T07:19:27.973894+00:00"
}